/* StockAI · app-i18n.js — interface language + LANG dictionary (loaded first) */
/* יומן שגיאות — נשמר במכשיר ומוצג בדוח האבחון (ℹ️), כדי שנוכל לאבחן תקלות גם בטלפון */
(function(){function log(m,src,line){try{var a=JSON.parse(localStorage.getItem('stockai_errlog')||'[]');a.push({t:new Date().toISOString(),m:String(m).slice(0,240),s:String(src||'').split('/').pop().split('?')[0],l:line||0});localStorage.setItem('stockai_errlog',JSON.stringify(a.slice(-10)));}catch(e){}}
window.addEventListener('error',function(e){if(e&&e.message)log(e.message,e.filename,e.lineno);});
window.addEventListener('unhandledrejection',function(e){var r=e&&e.reason;log('Promise: '+(r&&(r.message||r)),'','');});})();

var curLang=localStorage.getItem('stockai_lang')||'he';
var LANG={
en:{subtitle:'US & Israel Markets — Real-time AI — Market Sentiment',searchLabel:'◈ Enter a stock symbol to analyze',placeholder:'AAPL / TSLA / TEVA...',btnAnalyze:'▶ Analyze',btnAnalyzing:'Analyzing...',loadStep1:'◈ Scanning real-time market data...',loadStep2:'◈ Checking analyst recommendations...',loadStep3:'◈ Analyzing social media sentiment...',loadStep4:'◈ Processing financial data...',metricPrice:'Current Price',metricTarget:'Price Target',metricAnalyst:'Analyst Rating',metricRisk:'Risk Level',confLabel:'Recommendation Confidence',secSummary:'◈ Analysis Summary',secBull:'▲ Bullish Factors',secBear:'▼ Bearish Factors',sigSocial:'Social Sentiment',sigTech:'Technical Signal',sigFund:'Fundamental Score',secSources:'◈ Sources',historyLabel:'◈ Recent Analyses',disclaimer:'⚠ For research purposes only — not investment advice. All decisions are solely the investor\'s responsibility.',errGeneral:'Error analyzing stock',errNoAI:'⚠ No AI connected. Please tap ⚙ to connect your AI first.',recBuy:'BUY',recSell:'SELL',recHold:'HOLD',riskLow:'Low',riskMed:'Medium',riskHigh:'High',sentPos:'Positive',sentNeu:'Neutral',sentNeg:'Negative',techUp:'Rising',techDown:'Falling',techNeu:'Neutral',confHigh:'High',confMed:'Medium',confLow:'Low',shareBtn:'⬡ Share App',shareTitle:'StockAI — Smart Stock Analysis',shareText:'Discover StockAI — Real-time AI stock analysis for US & Israel markets.',moreApps:'More apps by AppNest',watchlistBtn:'◈ Watchlist',watchPanelTitle:'My Watchlist',tabMine:'My Stocks',tabIsrael:'Israel Top',tabUS:'US Top',addPlaceholder:'Add symbol...',addBtn:'+ Add',analyzeAll:'▶ Analyze All',watchEmpty:'Your watchlist is empty.\nAdd stocks to track them.',watchEmptyIcon:'◈',backupExport:'⬇ Export',backupImport:'⬆ Import',addToWatch:'+ Watchlist',addedToWatch:'✓ Watching',analyzeBtn:'▶ Analyze',staleMsg:'Analysis from {ago} ago',staleRefresh:'↺ Refresh',pwaTitle:'Install StockAI',pwaText:'Add to home screen — use as an app!',pwaInstall:'Install',pwaDismiss:'Not now',aiConnected:'Connected',aiNotConnected:'Not connected',aiSetupTitle:'Connect Your AI',guideTitle:'User Guide',guideTab1:'App Guide',guideTab5:'On-Device'},
he:{subtitle:'בורסות ארה"ב וישראל — AI בזמן אמת — סנטימנט שוק',searchLabel:'◈ הזן סימבול מניה לניתוח',placeholder:'AAPL / TSLA / TEVA...',btnAnalyze:'▶ נתח',btnAnalyzing:'מנתח...',loadStep1:'◈ סורק נתוני שוק בזמן אמת...',loadStep2:'◈ בודק המלצות אנליסטים...',loadStep3:'◈ מנתח סנטימנט רשתות חברתיות...',loadStep4:'◈ מעבד נתונים פיננסיים...',metricPrice:'מחיר נוכחי',metricTarget:'יעד מחיר',metricAnalyst:'דירוג אנליסטים',metricRisk:'רמת סיכון',confLabel:'רמת ביטחון בהמלצה',secSummary:'◈ סיכום ניתוח',secBull:'▲ גורמים חיוביים',secBear:'▼ גורמים שליליים',sigSocial:'סנטימנט חברתי',sigTech:'אינדיקטור טכני',sigFund:'ציון פנדמנטלי',secSources:'◈ מקורות',historyLabel:'◈ ניתוחים אחרונים',disclaimer:'⚠ למטרות מחקר בלבד — אינה ייעוץ השקעות.',errGeneral:'שגיאה בניתוח המניה',errNoAI:'⚠ לא מחובר ל-AI. לחץ ⚙ כדי לחבר את ה-AI שלך.',recBuy:'קנה',recSell:'מכור',recHold:'החזק',riskLow:'נמוך',riskMed:'בינוני',riskHigh:'גבוה',sentPos:'חיובי',sentNeu:'ניטרלי',sentNeg:'שלילי',techUp:'עולה',techDown:'יורד',techNeu:'ניטרלי',confHigh:'גבוה',confMed:'בינוני',confLow:'נמוך',shareBtn:'⬡ שתף',shareTitle:'StockAI — ניתוח מניות חכם',shareText:'גלה את StockAI — אנליזת מניות בזמן אמת עם AI.',moreApps:'עוד אפליקציות AppNest',watchlistBtn:'◈ מעקב',watchPanelTitle:'רשימת המעקב שלי',tabMine:'המניות שלי',tabIsrael:'מובילות ישראל',tabUS:'מובילות ארה"ב',addPlaceholder:'הוסף סימבול...',addBtn:'+ הוסף',analyzeAll:'▶ נתח הכל',watchEmpty:'רשימת המעקב שלך ריקה.\nהוסף מניות לעקוב אחריהן.',watchEmptyIcon:'◈',backupExport:'⬇ גבה',backupImport:'⬆ שחזר',addToWatch:'+ מעקב',addedToWatch:'✓ במעקב',analyzeBtn:'▶ נתח',staleMsg:'ניתוח מלפני {ago}',staleRefresh:'↺ רענן',pwaTitle:'התקן את StockAI',pwaText:'הוסף למסך הבית — השתמש כאפליקציה!',pwaInstall:'התקן',pwaDismiss:'לא עכשיו',aiConnected:'מחובר',aiNotConnected:'לא מחובר',aiSetupTitle:'חבר את ה-AI שלך',guideTitle:'מדריך משתמש',guideTab1:'מדריך האפליקציה',guideTab5:'במכשיר'},
ru:{subtitle:'Биржи США и Израиля — ИИ в реальном времени — Настроения рынка',searchLabel:'◈ Введите тикер акции для анализа',placeholder:'AAPL / TSLA / TEVA...',btnAnalyze:'▶ Анализ',btnAnalyzing:'Анализирую...',loadStep1:'◈ Сканирование рыночных данных...',loadStep2:'◈ Проверка рекомендаций...',loadStep3:'◈ Анализ настроений в соцсетях...',loadStep4:'◈ Обработка финансовых данных...',metricPrice:'Текущая цена',metricTarget:'Целевая цена',metricAnalyst:'Рейтинг аналитиков',metricRisk:'Уровень риска',confLabel:'Уверенность в рекомендации',secSummary:'◈ Резюме',secBull:'▲ Позитивные факторы',secBear:'▼ Негативные факторы',sigSocial:'Соц. настроения',sigTech:'Технический сигнал',sigFund:'Фундаментальный балл',secSources:'◈ Источники',historyLabel:'◈ Последние анализы',disclaimer:'⚠ Только для исследований — не инвестиционный совет.',errGeneral:'Ошибка анализа акции',errNoAI:'⚠ ИИ не подключён. Нажмите ⚙ для настройки.',recBuy:'КУПИТЬ',recSell:'ПРОДАТЬ',recHold:'ДЕРЖАТЬ',riskLow:'Низкий',riskMed:'Средний',riskHigh:'Высокий',sentPos:'Позитивный',sentNeu:'Нейтральный',sentNeg:'Негативный',techUp:'Рост',techDown:'Падение',techNeu:'Нейтральный',confHigh:'Высокая',confMed:'Средняя',confLow:'Низкая',shareBtn:'⬡ Поделиться',shareTitle:'StockAI — Умный анализ акций',shareText:'Откройте StockAI — анализ акций с ИИ в реальном времени.',moreApps:'Другие приложения AppNest',watchlistBtn:'◈ Список',watchPanelTitle:'Мой список слежения',tabMine:'Мои акции',tabIsrael:'Топ Израиль',tabUS:'Топ США',addPlaceholder:'Добавить тикер...',addBtn:'+ Добавить',analyzeAll:'▶ Анализировать всё',watchEmpty:'Список слежения пуст.\nДобавьте акции.',watchEmptyIcon:'◈',backupExport:'⬇ Экспорт',backupImport:'⬆ Импорт',addToWatch:'+ Слежение',addedToWatch:'✓ Слежу',analyzeBtn:'▶ Анализ',staleMsg:'Анализ {ago} назад',staleRefresh:'↺ Обновить',pwaTitle:'Установить StockAI',pwaText:'Добавьте на главный экран!',pwaInstall:'Установить',pwaDismiss:'Не сейчас',aiConnected:'Подключён',aiNotConnected:'Не подключён',aiSetupTitle:'Подключить ИИ',guideTitle:'Руководство',guideTab1:'Руководство',guideTab5:'На устройстве'},
es:{subtitle:'Bolsas de EEUU e Israel — IA en tiempo real — Sentimiento del mercado',searchLabel:'◈ Ingresa el símbolo de una acción',placeholder:'AAPL / TSLA / TEVA...',btnAnalyze:'▶ Analizar',btnAnalyzing:'Analizando...',loadStep1:'◈ Escaneando datos de mercado...',loadStep2:'◈ Revisando recomendaciones...',loadStep3:'◈ Analizando sentimiento social...',loadStep4:'◈ Procesando datos financieros...',metricPrice:'Precio actual',metricTarget:'Precio objetivo',metricAnalyst:'Calificación',metricRisk:'Riesgo',confLabel:'Confianza en la recomendación',secSummary:'◈ Resumen',secBull:'▲ Factores positivos',secBear:'▼ Factores negativos',sigSocial:'Sentimiento social',sigTech:'Señal técnica',sigFund:'Puntuación fundamental',secSources:'◈ Fuentes',historyLabel:'◈ Análisis recientes',disclaimer:'⚠ Solo para investigación — no es asesoramiento de inversión.',errGeneral:'Error al analizar',errNoAI:'⚠ Sin IA conectada. Toca ⚙ para conectar tu IA.',recBuy:'COMPRAR',recSell:'VENDER',recHold:'MANTENER',riskLow:'Bajo',riskMed:'Medio',riskHigh:'Alto',sentPos:'Positivo',sentNeu:'Neutral',sentNeg:'Negativo',techUp:'Subiendo',techDown:'Bajando',techNeu:'Neutral',confHigh:'Alta',confMed:'Media',confLow:'Baja',shareBtn:'⬡ Compartir',shareTitle:'StockAI — Análisis de Acciones',shareText:'Descubre StockAI — Análisis de acciones con IA en tiempo real.',moreApps:'Más apps de AppNest',watchlistBtn:'◈ Lista',watchPanelTitle:'Mi lista de seguimiento',tabMine:'Mis acciones',tabIsrael:'Top Israel',tabUS:'Top EEUU',addPlaceholder:'Agregar símbolo...',addBtn:'+ Agregar',analyzeAll:'▶ Analizar todo',watchEmpty:'Tu lista está vacía.\nAgrega acciones.',watchEmptyIcon:'◈',backupExport:'⬇ Exportar',backupImport:'⬆ Importar',addToWatch:'+ Seguir',addedToWatch:'✓ Siguiendo',analyzeBtn:'▶ Analizar',staleMsg:'Análisis de hace {ago}',staleRefresh:'↺ Actualizar',pwaTitle:'Instalar StockAI',pwaText:'¡Agrega a la pantalla de inicio!',pwaInstall:'Instalar',pwaDismiss:'Ahora no',aiConnected:'Conectado',aiNotConnected:'No conectado',aiSetupTitle:'Conectar tu IA',guideTitle:'Guía de usuario',guideTab1:'Guía',guideTab5:'En dispositivo'},
ar:{subtitle:'أسواق الولايات المتحدة وإسرائيل — ذكاء اصطناعي فوري — معنويات السوق',searchLabel:'◈ أدخل رمز السهم للتحليل',placeholder:'AAPL / TSLA / TEVA...',btnAnalyze:'▶ تحليل',btnAnalyzing:'جارٍ التحليل...',loadStep1:'◈ مسح بيانات السوق...',loadStep2:'◈ فحص توصيات المحللين...',loadStep3:'◈ تحليل مشاعر التواصل الاجتماعي...',loadStep4:'◈ معالجة البيانات المالية...',metricPrice:'السعر الحالي',metricTarget:'السعر المستهدف',metricAnalyst:'تقييم المحللين',metricRisk:'مستوى المخاطرة',confLabel:'مستوى الثقة بالتوصية',secSummary:'◈ ملخص التحليل',secBull:'▲ عوامل إيجابية',secBear:'▼ عوامل سلبية',sigSocial:'المشاعر الاجتماعية',sigTech:'الإشارة التقنية',sigFund:'النقاط الأساسية',secSources:'◈ المصادر',historyLabel:'◈ آخر التحليلات',disclaimer:'⚠ للبحث فقط — لا تمثل نصيحة استثمارية.',errGeneral:'خطأ في تحليل السهم',errNoAI:'⚠ لا يوجد ذكاء اصطناعي متصل. اضغط ⚙ للإعداد.',recBuy:'شراء',recSell:'بيع',recHold:'احتفاظ',riskLow:'منخفض',riskMed:'متوسط',riskHigh:'مرتفع',sentPos:'إيجابي',sentNeu:'محايد',sentNeg:'سلبي',techUp:'صاعد',techDown:'هابط',techNeu:'محايد',confHigh:'عالٍ',confMed:'متوسط',confLow:'منخفض',shareBtn:'⬡ مشاركة',shareTitle:'StockAI — تحليل ذكي للأسهم',shareText:'اكتشف StockAI — تحليل الأسهم بالذكاء الاصطناعي الفوري.',moreApps:'مزيد من تطبيقات AppNest',watchlistBtn:'◈ متابعة',watchPanelTitle:'قائمة متابعتي',tabMine:'أسهمي',tabIsrael:'أفضل إسرائيل',tabUS:'أفضل أمريكا',addPlaceholder:'أضف رمزاً...',addBtn:'+ إضافة',analyzeAll:'▶ تحليل الكل',watchEmpty:'قائمتك فارغة.\nأضف أسهماً لمتابعتها.',watchEmptyIcon:'◈',backupExport:'⬇ تصدير',backupImport:'⬆ استيراد',addToWatch:'+ متابعة',addedToWatch:'✓ متابعة',analyzeBtn:'▶ تحليل',staleMsg:'تحليل منذ {ago}',staleRefresh:'↺ تحديث',pwaTitle:'تثبيت StockAI',pwaText:'أضف إلى الشاشة الرئيسية!',pwaInstall:'تثبيت',pwaDismiss:'ليس الآن',aiConnected:'متصل',aiNotConnected:'غير متصل',aiSetupTitle:'ربط الذكاء الاصطناعي',guideTitle:'دليل المستخدم',guideTab1:'الدليل',guideTab5:'على الجهاز'}
};
function T(k){return(LANG[curLang]&&LANG[curLang][k])||(LANG.en&&LANG.en[k])||k;}
function setLang(lang){
  curLang=lang;localStorage.setItem('stockai_lang',lang);
  var body=document.getElementById('appBody');
  if(lang==='he'||lang==='ar'){body.className=body.className.replace(/\bltr\b|\brtl\b/g,'').trim()+' rtl';document.documentElement.setAttribute('dir','rtl');}
  else{body.className=body.className.replace(/\bltr\b|\brtl\b/g,'').trim()+' ltr';document.documentElement.setAttribute('dir','ltr');}
  if(lang==='ar')body.classList.add('ar-lang');else body.classList.remove('ar-lang');
  document.documentElement.setAttribute('lang',lang);
  document.querySelectorAll('.lang-btn').forEach(function(b){b.classList.remove('active');});
  var ab=document.getElementById('lang-'+lang);if(ab)ab.classList.add('active');
  renderText();renderWatchlist();
}
function renderText(){
  document.querySelectorAll('[data-t]').forEach(function(el){el.textContent=T(el.getAttribute('data-t'));});
  document.querySelectorAll('[data-tp]').forEach(function(el){el.placeholder=T(el.getAttribute('data-tp'));});
  var d=document.getElementById('disclaimer');if(d)d.textContent=T('disclaimer');
  updateAIStatus();
}
;(window.__MODS=window.__MODS||{})['app-i18n']=1;
